---
title: "Team Contribution Report"
output: pdf_document
author: "Tyler Yankee, Joseph LaPell, Minsun Kim"
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General Overview of Project

Our group's part of the bikeshare data analysis attempted to determine the extent to which people in Washington D.C. use the Capital Bikeshare system for the "final mile" of their commute to work; that is, they ride the metro for the majority of their commute, get off the metro and get a bike nearby, and use that bike for a short ride to make up the remainder of their commute. 
## Assumptions

The following assumptions were made in conducting this analysis:

* Data was taken from September 2022 Capital Bikeshare; a more representative analysis would have taken into account other parts of the year. 
* We enforced that the metro station and the start bikeshare station were within 500 ft of each other, and that the bike ride was less than 1 mile. 
* Every ride that fits these constraints was a "final mile" ride (i.e., pertaining to that person's commute). This is the major assumption that could damage the validity of the analysis as it is not necessarily true in all cases.

## Breakdown and File Structure

The analysis was segmented into three major parts:

* Analyze grouped data on metro stations through distributions and comparing counts and average distances. Visualize these through density plots, histograms, bar plots, and maps. (Done in `FinalMile_Stations.Rmd`.)
* Join LODES job data with bikeshare end points that fall within the "final mile" category to determine if areas with more jobs also have more "final mile" rides. (Done in `FinalMile_LaPell.Rmd`.)
* Calculate proportion of rides within 500 ft of a station that are final mile rides. Compare this proportion across different metro stations. (Done in `FinalMile_proportion of rides.Rmd`.)

The base of all of the analysis was done in `FinalMile_Original.Rmd`.


# Member Contributions

## Tyler Yankee

I was responsible for the first bullet point above under "Breakdown." I worked on `FinalMile_Stations.Rmd`, which builds on `FinalMile_Original` by grouping the data by metro station. The following questions are addressed in this file through mostly exploratory analysis:

* Which metro station(s) are the most popular for "final mile" rides? (Bar plot and map)
* How many bikeshare stations are within 500 ft of each metro station, and how far away are they (faceted histogram and map)?
* How far is the average "final mile" ride from each metro station? What is the distribution of this distance?

In addition, the key data frames for analysis are output to csv in the data/ directory:

* final_mile_rides.csv: For each "final mile" bikeshare ride, show the name of the metro station within 500 ft, the name of the starting bikeshare station, the distance between the stations, and the bike ride distance.
* final_mile_metro.csv: For each metro station, show the name, the number of "final mile" rides which stemmed from the given metro station, the average distance from the metro to the bikeshare station, and the average distance of the ensuing bike ride.
* final_mile_metro.geojson: Same as the above .csv, but formatted as a .geojson with the point geometry listed for each metro station.
* close_metro_bikeshare_stations.geojson: All pairings of metro stations and bikeshare stations in Washington D.C which are within 500 ft of each other.


## Joseph LaPell

My contributions to this project included the second bullet point under "Breakdown," where I joined the LODES data with Final Mile data and created some visualizations for it. Along with that, I also had a part in creating the FinalMileOriginal.Rmd, i.e. creating the dataframe that contained bike ride start points within 500 feet of a station, then creating another dataframe that contained rides that were under a mile from start to end.

After combining and analyzing the LODES/bike-ride data, there wasn't much to take away. If the individual rides had more information, such as different characteristics of the rider, it would be easier to compare with the LODES data. If there were characteristics such as age, gender, race, etc. connected with the bikeshare data, I would be able to filter the job data and compare it with the bikeshare data and possibly draw a conclusion. The fact is though, that there are already a few assumptions being made. One of these assumptions include that every bike start point within 500 feet of a metro station is someone who got off the metro. That being said it is hard to draw any concrete conclusions from the data, but it still is interesting to look at the visualizations. 

## Minsum Kim
Looking for the definition of Final miles, they have two conditions. one is the bikeshare station should exist nearby in 500ft from the metro station, and second is the total ride distance should not be over 1 mile. I calculate the proportion of rides which is less than 1 mile, in other words the proportion of final mile rides. 

I filtered the data, one is limited by 1 mile, and the other is not limited by 1 mile, and calculated proportion and grouped by metro station, In other words I calculated the proportion of final mile rides group by metro, and made visualization to compare to each metro station. Also I figured out what happend for outlier data.

## Dante Joefield 
I helped contribute to the extension part of the bike share data. I helped come up with the idea of seeing how close a bike station was to a metro a station. With that idea we were allowed to analyze different aspects of the bike share data.
