---
title: "LastMile"
author: "Joseph LaPell"
date: "2022-11-21"
output: html_document
---
```{r}
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(sf)
library(tmap)
library(geojsonsf)
library(matrixStats)
library(geosphere)
bikeshare = read_csv(here("data_raw", "202209-capitalbikeshare-tripdata.zip")) %>%
  clean_names()
metro_stations = read_csv(here("data_raw", "Metro_Stations_in_DC.csv")) %>%
  clean_names()
```

# Just doing a sample for a monday, this is for September 5, 2022, the first monday of the month.
```{r}
bikeshare1 = bikeshare %>% filter(grepl("2022-09-05 ", started_at)) %>% select(end_station_name,lat = end_lat, lng = end_lng) %>% na.omit() 
metro_stations1 = metro_stations %>% select(end_station_name = name, lat = y, lng = x) %>% na.omit()
```

# https://stackoverflow.com/questions/58831578/minimum-distance-between-lat-long-across-multiple-data-frames
#Finds the closest station to bikes endpoint, adds station name and distance to the bikshare dataframe.

```{r}
#calculate the distance matrix
distmatrix<-distm(bikeshare1[, c(3, 2)], metro_stations1[,c(3, 2)])
#find closest column and get distance
closest<-apply(distmatrix, 1, which.min)
bikeshare1$close_station <- as.character(metro_stations1$end_station_name[closest])
bikeshare1$distance <- apply(distmatrix, 1, min)/1000
```

# Counts the amount of bikes parked within .1524km/500ft, close enough to consider bike being used for final mile.
```{r}
final_mile = bikeshare1 %>% filter(distance < .1524)
nrow(final_mile)
```



